### ISSUE TITLE
feat: Support for Gradient Linear Progress Indicator

### ISSUE THREAD

**Issue by PranavMasekar** [mkobuolys/flutter_deck#29]
**Description**

Currently flutter_deck supports only a linear progress indicator with no customization options. So adding support for some animated gradient linear progress indicator can be helpful.

**Requirements**

[ ] Customization Options for progress indicator
[ ] Changing implementation of Linear Progress Indicator

**Additional Context**

I am suggesting to use this package for the implementation - 

https://pub.dev/packages/simple_animation_progress_bar

@mkobuolys Let me know your thaughts on this.

Add any other context or screenshots about the feature request go here.

**Comment by mkobuolys** [comment]
Hey, thanks for the suggestion! Not a priority feature, for sure, but we can implement it, why not?

However, I would prefer not to use this package since implementing a gradient progress indicator is literally just a few lines of code. For instance:

```dart
const progress = 0.69; // Progress value 0.0 -> 1.0

LayoutBuilder(
  builder: (context, constraints) {
    final maxWidth = constraints.maxWidth;
    final indicatorWidth = maxWidth * progress;

    return Container(
      height: 8.0,
      width: maxWidth,
      color: Colors.grey,
      child: Align(
        alignment: Alignment.centerLeft,
        child: Container(
          width: indicatorWidth,
          decoration: const BoxDecoration(
            gradient: LinearGradient(
              colors: [Colors.black, Colors.purple],
            ),
          ),
        ),
      ),
    );
  },
);
```

The animation is also not needed since based on the current implementation, the progress indicator is rendered individually for each page (slide), thus you won't see the animation taking effect. You can try to implement a wrapper around the whole slide deck, of course, and see how it goes.

If you want to work on the issue, here is my suggestion on how to approach it:
1) Move the current `FlutterDeckProgressIndicator` from the internal widgets directory to widgets (so that users can use it);
2) Support two constructors: `FlutterDeckProgressIndicator.solid` and `FlutterDeckProgressIndicator.gradient`. The solid constructor accepts a single colour while the gradient one accepts the gradient object (check how the `FlutterDeckBackground` widget is implemented). Then, apply the right styling for the indicator.
3) Add a new configuration value to the `FlutterDeckConfiguration` - `progressIndicator`. It should be optional. If no `progressIndicator` is provided, use the default one (`FlutterDeckProgressIndicator.solid` with a primary colour from the theme.
4) Update docs and README where needed.

How does it sound?

**Comment by PranavMasekar** [comment]
@mkobuolys Sure sound perfect to me. I will get starting with this then and let you know if any issues are there.

**Comment by PranavMasekar** [comment]
@mkobuolys I have implemented all the things that you mentioned above but was facing an issue regarding giving primary color to .solid constructor. 

From where does that primary color you mentioned come from ?? 

![image](https://github.com/mkobuolys/flutter_deck/assets/83063593/67228235-0742-40d5-b5f3-4c0567290724)

**Comment by mkobuolys** [comment]
> @mkobuolys I have implemented all the things that you mentioned above but was facing an issue regarding giving primary color to .solid constructor.
> 
> From where does that primary color you mentioned come from ??
> 
> For now I have added a hard coded color to test the logic. But can you help me with this ?
> 
> ![image](https://user-images.githubusercontent.com/83063593/275305153-67228235-0742-40d5-b5f3-4c0567290724.png)

You should not pass the default colour here, but rather, keep a default constructor. Then, since the colour and gradient is not set, inside the indicator widget, you can use the primary colour from the theme.

**Comment by PranavMasekar** [comment]
@mkobuolys 

![image](https://github.com/mkobuolys/flutter_deck/assets/83063593/81a63f0e-92f6-4f26-ab44-82f46d038cc6)

I have done like this .

**Comment by mkobuolys** [comment]
Could you just create a pull request? It would be easier to communicate and find issues.

**Comment by PranavMasekar** [comment]
Sure
