### ISSUE TITLE
feat: mobile responsiveness support

### ISSUE THREAD

**Issue by burkaslarry** [mkobuolys/flutter_deck#44]
**Summary**

First of all , thank you for your consistent work on flutter_deck. I help Deep Tech Girl Foundation to prepare slides to provide teaching git to other teenagers or adult who wants another career path to IT industry. 

In case for allowing mobile user to read the slides, I would to like to make requests on 

<img width="1190" alt="Screenshot 2023-12-16 at 8 33 06 PM" src="https://github.com/mkobuolys/flutter_deck/assets/5709615/bceccbde-0949-4e88-951f-b5ae486f9364">

Clearly describe what you are looking to add. The more context the better.

**Requirements**

- [ ] Mobile responsiveness on reading slides on smartphone/ tablets 
- [ ] Mouse click to left section / right section to more previous / next slide 
- [ ] Widget Text under social handle section should support html feature to allow user to click 
- [ ] Add elapsed time count per slides to track speaker on how long the slide has presented. 
- [ ] Floating button to save a list of questions so that Q And A slides can be dynamically generated to increase interactions. 

**Additional reminders**

I love using this as a means to provide interactive sharing among audience, both for software dev beginners and experts.  I would like to see if I can directly folk this project and enhance the slides dependency.  This is awesome together with using vercel for fast CI/CD.

**Comment by mkobuolys** [comment]
Hey @burkaslarry, thank you so much for your input! I will go point by point there:

> Mobile responsiveness on reading slides on smartphone/ tablets

I am happy I can share some progress here. With https://github.com/mkobuolys/flutter_deck/commit/f61e835929b508f10ed49d43a71469ec466e7057, I added the scaling option to the flutter_deck. It keeps the specified aspect ratio and scales the content based on the view size. It's not released yet, though. However, the demo is already available here: https://mkobuolys.github.io/flutter_deck/

> Mouse click to left section / right section to more previous / next slide

This is literally the next item on my to-do list. Since scaling is supported, after implementing this I will release the next version of the package that will make the slides usable on mobile (or just smaller screen size) devices.

> Widget Text under social handle section should support html feature to allow user to click

To be honest, I do not see this as an out-of-the-box feature, MAYBE some kind of different variant for the footer. However, you can pass a custom widget to the footer, so it should not be too complex to implement yourself once needed. Example: https://github.com/mkobuolys/flutter_deck/blob/main/example/lib/slides/footer_slide.dart

> Add elapsed time count per slides to track speaker on how long the slide has presented.

I see this more as a part of a speaker's view rather than the slide deck you show to the audience. At the moment, there are some blockers to start working on it. You can follow the discussion here: https://github.com/mkobuolys/flutter_deck/issues/10

> Floating button to save a list of questions so that Q And A slides can be dynamically generated to increase interactions.

Ooo, this is a nice one. It sounds like you want something that the audience would be able to join your currently running presentation and they can interact with it (e.g. leave questions). It sounds like a back-end or cloud service is needed to store questions, thus it won't probably be supported by the package itself (unless some kind of SaaS is created around it). Would love to see the PoC if you have time and ideas to implement it 😃 

This is great feedback, let me know if you have any more questions ✌️

**Comment by mkobuolys** [comment]
> Mouse click to left section / right section to more previous/next slide
Status update: yesterday, a flutter_deck version of v0.9.1 was released that includes the slide deck controls widget. It allows you to control the deck in even more ways than just going to the next/previous slide. You can check the updated [demo](https://mkobuolys.github.io/flutter_deck/).

**Comment by burkaslarry** [comment]
Great Thanks. I shall add that to my slides afterwards.
