### ISSUE TITLE
feat: Deck Playlists with auto playback

### ISSUE THREAD

**Issue by jtkeyva** [mkobuolys/flutter_deck#52]
**Description**

Say I have 3 decks about cars and 3 decks about food. I would want to be able to play all the car decks on auto play (haha no pun intended). Another time i would want a playlist called Food where it plays all my food decks. And another option to simply play all decks.

**Requirements**

- [ ] Create playlists
- [ ] Autoplay
- [ ] Loop mode
- [ ] Play all decks
- [ ] Deck library/catalog

**Additional Context**

This could become a general media player and be used for TVs

**Comment by mkobuolys** [comment]
Hey @jtkeyva, thanks for your input! I am a bit sceptical about this since I am not aware of any slide framework working this way. Also, presentation is run as a stand-alone Flutter app, thus I am trying to wrap my head around the fact about running multiple presentations. Like, you need to handle different apps, run/dismount them and so on, which does not sound right. Usually, if you have such cases, you just copy/paste the content into a single presentation and run it as one.

However, I totally agree with the Autoplay feature and it is one of the top-most items on my to-do list ✌️

**Comment by jtkeyva** [comment]
@mkobuolys i understand...i don't see any other slide framework running that way either necessarily but i see a more general presentation utility potential. if you end goal is to stick to a slide framework then maybe it's not for you. i just see a lot of potential combining the 2.

essentially all these things are doing is showing a series of things. might as well be able to show a series of series if it's not too much work. like you take a story player and it plays groups of content. so one presentation would be one group of content. there is no running separate apps or dismounting. it's just playing content. maybe you have a few loaded into memory and then unloaded like the https://pub.dev/packages/preload_page_view

look forward to see where this headed. actually, what is your goal with this package? i'm trying to decide if i am going to use my own app or build it upon some packages.

thank you

**Comment by mkobuolys** [comment]
The goal of the package is to use it for creating presentation slides in Flutter. The package should care of all the implementation details that the author of the slides should not care about (navigation, controls, layouts, some of the key widgets, etc.) and only focus on creating the content. Thus, I do not see how flutter_deck could be run as a sub-package in any other project - it should be the root app. This is the main difference between this and other page views or story slides you provided.

**Comment by jtkeyva** [comment]
aha i understand. you have done a great job of making it simple to add content and navigate. i look forward to seeing what's next. kudos!

**Comment by jtkeyva** [comment]
@mkobuolys are you still stuck on keeping this as a one trick pony single root app framework? wouldn't you think it could be very useful within an app for various general purposes? i understand you setting the config at the root level  kinda removes the dynamic potential but there's a lot of opportunity here ad a general presentation tool as well. thoughts still the same?

**Comment by mkobuolys** [comment]
Yup, I feel that the main purpose of the framework is to have a single presentation per `FlutterDeckApp`. If you want to use something custom what you mentioned:
a) Wrap `FlutterDeckApp` with a custom widget that handles the slides' selection (e.g. you select 2 presentations about cars). Then, the chosen slides' (imagine, slide lists) are merged into one and passed to `FlutterDeckApp`.
b) Wrap `FlutterDeckApp` with some kind of `ValueNotifier` that stores the ID of the current presentation. Based on the selected ID, the specific presentation is rendered. Then, in the last slide of each presentation, you can add a listener to update the ID in the notifier, hence rendering the next presentation.

Anyway, what you defined in the issue is to have some presentation editor, where you can select what slides must be included, what's the configuration, etc. However, it sounds like something a level above `flutter_deck` (think of a visual editor), but I see `flutter_deck` more of an engine that runs a single presentation.

**Comment by jtkeyva** [comment]
fair enough. thanks for the tip, sounds like a lazy infinite scroll type of solution...i will give it a shot to see if it fits my scenario
