### ISSUE TITLE
fix: when `enabled: false` in controls config, shortcuts also cease to work

### ISSUE THREAD

**Issue by GregoryConrad** [mkobuolys/flutter_deck#53]
**Description**

The new control widget introduced in v0.9 is a great addition, but when going to present, it can get in the way.
Thus, when I went to:
```dart
          controls: const FlutterDeckControlsConfiguration(
            enabled: false,
            shortcutsEnabled: true,
            openDrawerKey: LogicalKeyboardKey.arrowUp,
            toggleMarkerKey: LogicalKeyboardKey.arrowDown,
          ),
```
The controls were hidden as expected, but my keyboard shortcuts stopped working (drawer, left/right arrow key, marker).

**Comment by GregoryConrad** [comment]
Well, I actually just realized the control widget disappears when there is no mouse activity for a few seconds so I am actually fine leaving `enabled: true`.  But this may still be a bug?

**Comment by mkobuolys** [comment]
Hi @GregoryConrad, I have also thought about this. TL;DR: **it may be a bug**. At the moment, the `enabled: false` flag completely disables all controls for the slide. I think this could be useful if you want to autoplay your slide deck or trigger slide changes with your custom buttons/controller in slides by calling `context.flutterDeck.next()` or `context.flutterDeck.previous()`. Now, when I said that, I don't think it works this way since the whole control logic is not added to the tree, I need to double-check it 😅 

If you have any suggestions for a clearer API, let me know. I am also thinking about adding touch controls (swipe left/right or press on the left/right part of the slide to navigate).

**Comment by GregoryConrad** [comment]
Maybe you could also have a “showPanel” attribute to hide the controls, in addition to “enabled” and “shortcutsEnabled”? I’m not too tied to this though (once I realized the control panel auto-hides when the mouse doesn’t move), so you can do what you want!

**Comment by mkobuolys** [comment]
To be fair, I even think that the `enabled` flag is redundant and should be removed if we have `shortcutsEnabled` and `showPanel` flags 🤷‍♂️  Anyway, I will revisit this, for sure.

**Comment by mkobuolys** [comment]
Fixed with https://github.com/mkobuolys/flutter_deck/pull/55.
